 /* بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ  ﷺ  InshaAllah */
/* Allah is enough for me */
import { urlReducer } from "./reducer"

 


const actions =  {
//image
 ADD_IMAGE :'ADD_IMAGE' ,
 //meta
 ADD_METADATA : 'ADD_METADATA',
 ADD_METADATA_HEIGHT :'ADD_METADATA_HEIGHT',
 ADD_METADATA_WIDTH : 'ADD_METADATA_WIDTH',
 //url
 ADD_URL :'ADD_URL',
 SUCCESS_STATUS :'SUCCESS_STATUS',
 PENDING_STATUS : 'PENDING_STATUS',
 //filter
 ADD_CHANGE_OBJECT :'ADD_CHANGE_OBJECT',
 EMPTY_CHANGE_OBJECT :'EMPTY_CHANGE_OBJECT',
 ADD_FILTER_NONE : 'ADD_FILTER_NONE',
 ADD_FILTER_BLUR : 'ADD_FILTER_BLUR',
 ADD_FILTER_BRIGHTNESS : 'ADD_FILTER_BRIGHTNESS',
 ADD_FILTER_SATURATION :'ADD_FILTER_SATURATION',
 ADD_FILTER_HUE :'ADD_FILTER_HUE',
 ADD_FILTER_CONTRAST :'ADD_FILTER_CONTRAST',
 ADD_FILTER_OPACITY :'ADD_FILTER_OPACITY',
 ADD_FILTER_SCALE   :'ADD_FILTER_SCALE',
 ADD_FILTER_GRAYSCALE   :'ADD_FILTER_GRAYSCALE',
 ADD_FILTER_ROTATE : 'ADD_FILTER_ROTATE',
 REMOVE_FILTER : 'REMOVE_FILTER' ,
 //BUSY
 BUSY_TRUE :'BUSY_TRUE',
 BUSY_FALSE : 'BUSY_FALSE',
 //file
 ADD_FILE : 'CHANGE_FILE',
 //change Current Url
 CHANGE_CURRENT_URL :'CHANGE_CURRENT_URL',
 ADD_PREV_URL : 'ADD_PREV_URL' ,
 REMOVE_PREV_URL : 'REMOVE_PREV_URL',
 ADD_FORWARD_URL : 'ADD_FORWARD_URL' ,
 REMOVE_FORWARD_URL : 'REMOVE_FORWARD_URL',
 
}






export default actions









